export const COMMUNITY_LIST = "COMMUNITY_LIST";
export const COMMUNITY_UPDATE = "COMMUNITY_UPDATE";
export const COMMUNITY_PUBLISH = "COMMUNITY_PUBLISH";
export const COMMUNITY_DELETE = "COMMUNITY_DELETE";
